name: Test

on:
  push:
  pull_request:

jobs:
  validate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "15"

      - name: "npm: test"
        run: |
          npm install
          npm test